### ISSUE TITLE
Umbrella issue

### ISSUE THREAD

**Issue by jamespjh** [jamespjh/training-20190328#4]
- [x] The first task
- [ ] The second task
- [ ] The third task
